# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='date_modificada',
            new_name='data_modificada',
        ),
    ]
