# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170426_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='completa',
            field=models.BooleanField(default=False),
        ),
    ]
