# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170501_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
